services:
  details:
    build: details/
    image: ghcr.io/angellllegna/bookinfo-details:dev
    ports:
      - "8081:8081"
  ratings:
    build: ratings/
    image: ghcr.io/angellllegna/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - "./ratings/databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings
  reviews:
    build: reviews/
    image: ghcr.io/angellllegna/bookinfo-reviews:dev
    ports:
      - "8082:8082"
    environment:
      ENABLE_RATINGS: "true"
      STAR_COLOR: salmon 
      RATINGS_SERVICE: http://ratings:8080
  productpage:
    build: productpage/
    image: ghcr.io/angellllegna/bookinfo-productpage:dev
    ports:
      - "8083:8083"
    environment:
      DETAILS_HOSTNAME: http://details:8081
      REVIEWS_HOSTNAME: http://reviews:8082
      RATINGS_HOSTNAME: http://ratings:8080
